[build]
  repository = "https://github.com/AdamBabinicz/namioty-imprezowe"

  [[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; ..."
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
  Permissions-Policy = "geolocation=(self), microphone=()"

